global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "user-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["user-service:8000"]

  - job_name: "appointment-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["appointment-service:8000"]

  - job_name: "medical-records-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["medical-records-service:8000"]

  - job_name: "api-gateway"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["api-gateway:8000"]

  - job_name: "notification-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["notification-service:8000"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
